### ISSUE TITLE
Imagens coladas nas frases dos botões

### ISSUE THREAD

**Issue by joaopruinelli** [rocketseat-education/nlw-06-discover#1]
- Falta uma vírgula na linha [86](https://github.com/rocketseat-education/nlw6-discover/blob/c60c847f33186092c22b18f021391bc8bd554583/styles/global.css#L86) do arquivo "global.css". O que faz com que as imagens fiquem coladas nas frases dos botões.

Learn more about me:
- 🌱 Watch my personal studies on [GitHub](https://github.com/joaopruinelli);
- 💼 Connect with me on [LinkedIn](https://www.linkedin.com/in/jo%C3%A3o-vitor-pruinelli-a78649214/);
- 📷 Follow me on [Instagram](https://www.instagram.com/john_pruinelli/).

**Comment by jakeliny** [comment]
Foi corrigido na aula :D
